/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaraytracer.RayTracerUI;

import java.awt.BorderLayout;

/**
 *
 * @author deibh
 */
public class Materiales extends javax.swing.JFrame {

    /**
     * Creates new form Materiales
     */
    public Materiales() {
        initComponents();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Material1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        panel1 = new java.awt.Panel();
        jCheckBox1 = new javax.swing.JCheckBox();
        Material2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        panel2 = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        Material3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        panel3 = new java.awt.Panel();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(480, 690));
        setSize(new java.awt.Dimension(1147, 714));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Material1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Material1.setToolTipText("");
        Material1.setName(""); // NOI18N
        Material1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        Material1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 16, 56, -1));

        jLabel3.setText("Tipo de material");
        Material1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 59, 95, -1));

        jLabel4.setText("R");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 99, -1, -1));
        Material1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 96, 33, -1));

        jLabel5.setText("G");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 99, -1, -1));
        Material1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 96, 33, -1));

        jLabel6.setText("B");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 99, -1, -1));
        Material1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 96, 33, -1));
        Material1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 13, 92, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Material1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 53, 90, -1));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        Material1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jCheckBox1.setText("Activar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Material1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        getContentPane().add(Material1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 160));

        Material2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Material2.setToolTipText("");
        Material2.setName(""); // NOI18N
        Material2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nombre");
        Material2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 16, 56, -1));

        jLabel8.setText("Tipo de material");
        Material2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 59, 95, -1));

        jLabel9.setText("R");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 99, -1, -1));
        Material2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 96, 33, -1));

        jLabel10.setText("G");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 99, -1, -1));
        Material2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 96, 33, -1));

        jLabel11.setText("B");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 99, -1, -1));
        Material2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 96, 33, -1));
        Material2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 13, 92, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Material2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 53, 90, -1));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        Material2.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel12.setText("F");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 135, -1, -1));
        Material2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 132, 33, -1));

        jCheckBox2.setText("Activar");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        Material2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        getContentPane().add(Material2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 160));

        Material3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Material3.setToolTipText("");
        Material3.setName(""); // NOI18N
        Material3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Nombre");
        Material3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 16, 56, -1));

        jLabel14.setText("Tipo de material");
        Material3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 59, 95, -1));

        jLabel15.setText("R");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 99, -1, -1));
        Material3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 96, 33, -1));

        jLabel16.setText("G");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 99, -1, -1));
        Material3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 96, 33, -1));

        jLabel17.setText("B");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 99, -1, -1));
        Material3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 96, 33, -1));
        Material3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 13, 92, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Material3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 53, 90, -1));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        Material3.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel18.setText("F");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 131, -1, -1));
        Material3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 128, 33, -1));

        jCheckBox3.setText("Activar");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        Material3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        getContentPane().add(Material3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 380, 160));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        getAccessibleContext().setAccessibleName("Materiales");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Material1;
    private javax.swing.JPanel Material2;
    private javax.swing.JPanel Material3;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
