/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RaytracerUI;

import java.awt.BorderLayout;

/**
 *
 * @author deibh
 */
public class Materiales extends javax.swing.JFrame {

    /**
     * Creates new form Materiales
     */
    public Materiales() {
        initComponents();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Material1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        g1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        tm1 = new javax.swing.JComboBox<>();
        txtf1 = new javax.swing.JTextField();
        f1 = new javax.swing.JLabel();
        Material2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        g2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        b2 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        tm2 = new javax.swing.JComboBox<>();
        f2 = new javax.swing.JLabel();
        txtf2 = new javax.swing.JTextField();
        Material3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        r3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        g3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        b3 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        tm3 = new javax.swing.JComboBox<>();
        f3 = new javax.swing.JLabel();
        txtf3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(480, 690));
        setSize(new java.awt.Dimension(1147, 714));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Material1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Material1.setToolTipText("");
        Material1.setName(""); // NOI18N
        Material1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        Material1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 56, -1));

        jLabel3.setText("Tipo de material");
        Material1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 95, -1));

        jLabel4.setText("R");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        r1.setText("0.1");
        Material1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 33, -1));

        jLabel5.setText("G");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        g1.setText("0.2");
        Material1.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 33, -1));

        jLabel6.setText("B");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        b1.setText("0.5");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        Material1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 33, -1));

        jTextField4.setText("Hierro");
        Material1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 92, -1));

        tm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metal", "Roca", "Conductor" }));
        tm1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tm1ItemStateChanged(evt);
            }
        });
        Material1.add(tm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, -1));

        txtf1.setText("0");
        txtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf1ActionPerformed(evt);
            }
        });
        Material1.add(txtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 33, -1));

        f1.setText("F");
        f1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material1.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        getContentPane().add(Material1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 160));

        Material2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Material2.setToolTipText("");
        Material2.setName(""); // NOI18N
        Material2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nombre");
        Material2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 56, -1));

        jLabel8.setText("Tipo de material");
        Material2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 95, -1));

        jLabel9.setText("R");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        r2.setText("0.84");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        Material2.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 40, -1));

        jLabel10.setText("G");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        g2.setText("0.06");
        Material2.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 40, -1));

        jLabel11.setText("B");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 10, -1));

        b2.setText("0.34");
        Material2.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 40, -1));

        jTextField8.setText("Granito");
        Material2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 92, -1));

        tm2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metal", "Roca", "Conductor" }));
        tm2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tm2ItemStateChanged(evt);
            }
        });
        Material2.add(tm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        f2.setText("F");
        f2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material2.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtf2.setText("0");
        Material2.add(txtf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 33, -1));

        getContentPane().add(Material2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 160));

        Material3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Material3.setToolTipText("");
        Material3.setName(""); // NOI18N
        Material3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Nombre");
        Material3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 56, -1));

        jLabel14.setText("Tipo de material");
        Material3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 95, -1));

        jLabel15.setText("R");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        r3.setText("0.8");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        Material3.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 33, -1));

        jLabel16.setText("G");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        g3.setText("0.6");
        Material3.add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 33, -1));

        jLabel17.setText("B");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        b3.setText("0.5");
        Material3.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 33, -1));

        jTextField13.setText("Iman");
        Material3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 92, -1));

        tm3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metal", "Roca", "Conductor" }));
        tm3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tm3ItemStateChanged(evt);
            }
        });
        Material3.add(tm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        f3.setText("F");
        f3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Material3.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtf3.setText("0");
        Material3.add(txtf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 33, -1));

        getContentPane().add(Material3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, 160));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        getAccessibleContext().setAccessibleName("Materiales");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void tm1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tm1ItemStateChanged
       if(tm1.getItemAt(1)!= "Metal"){
           f1.setVisible(false);
           txtf2.setVisible(false);
       }
    }//GEN-LAST:event_tm1ItemStateChanged

    private void tm2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tm2ItemStateChanged
        if(tm3.getItemAt(1)!= "Metal"){
           f2.setVisible(false);
           txtf2.setVisible(false);
       }
    }//GEN-LAST:event_tm2ItemStateChanged

    private void tm3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tm3ItemStateChanged
       if(tm3.getItemAt(1)!= "Metal"){
           f3.setVisible(false);
           txtf3.setVisible(false);
       }
    }//GEN-LAST:event_tm3ItemStateChanged

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void txtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Material1;
    private javax.swing.JPanel Material2;
    private javax.swing.JPanel Material3;
    public static javax.swing.JTextField b1;
    public static javax.swing.JTextField b2;
    public static javax.swing.JTextField b3;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    public static javax.swing.JTextField g1;
    public static javax.swing.JTextField g2;
    public static javax.swing.JTextField g3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField r1;
    public static javax.swing.JTextField r2;
    public static javax.swing.JTextField r3;
    private javax.swing.JComboBox<String> tm1;
    private javax.swing.JComboBox<String> tm2;
    private javax.swing.JComboBox<String> tm3;
    private javax.swing.JTextField txtf1;
    private javax.swing.JTextField txtf2;
    private javax.swing.JTextField txtf3;
    // End of variables declaration//GEN-END:variables
}
