/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RaytracerUI;

import static java.awt.event.KeyEvent.VK_ENTER;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import Raytracer.Renderer;
import Raytracer.Scene;
import javax.swing.ImageIcon;
import Raytracer.RayTracer;
import Raytracer.Camera;
import Raytracer.Config;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author camil
 */
public class RayTracerUI extends javax.swing.JFrame {

    /**
     * Creates new form RayTracerUI
     */
        JFileChooser seleccionar = new JFileChooser();
        File archivo;
        byte[] imagen;
        FileOutputStream salida;
        Config config = new Config(Integer.parseInt(Configuracion.Ancho.getText()), Double.parseDouble(Configuracion.aspecto.getText()), Integer.parseInt(Configuracion.pixel.getText()), 20); 
    public RayTracerUI(Renderer renderer) {
        initComponents();
        
        this.renderer = renderer;
        e1activa.doClick();
        e2activa.doClick();
        e3activa.doClick();
        imagen();

        
       
        
    }
    
//    public RayTracerUI(Renderer renderer) {
//        this.renderer = renderer;
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Principal = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        lb_imagen = new javax.swing.JLabel();
        PanelEsferas = new javax.swing.JPanel();
        esfera1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_e1r = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_e1y = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_e1z = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_e1x = new javax.swing.JTextField();
        radioBar1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        e1activa = new javax.swing.JCheckBox();
        esfera2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txt_e2r = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_e2y = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_e2z = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_e2x = new javax.swing.JTextField();
        radioBar2 = new javax.swing.JSlider();
        jLabel28 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        e2activa = new javax.swing.JCheckBox();
        esfera3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_e3r = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_e3y = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_e3z = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_e3x = new javax.swing.JTextField();
        radioBar3 = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        e3activa = new javax.swing.JCheckBox();
        base = new javax.swing.JCheckBox();
        PanelCamara = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Cz1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_Cy1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Cx1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_Rx = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Ry = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_Rz = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Vertical = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_imagen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_imagen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lb_imagenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panelImagen.add(lb_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        Principal.add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 600, 650));

        PanelEsferas.setBackground(new java.awt.Color(248, 255, 255));
        PanelEsferas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEsferas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esfera1.setBackground(new java.awt.Color(255, 255, 255));
        esfera1.setBorder(javax.swing.BorderFactory.createTitledBorder("Esfera 1"));
        esfera1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Posicion:");
        esfera1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txt_e1r.setText("0.5");
        txt_e1r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_e1rActionPerformed(evt);
            }
        });
        txt_e1r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e1rKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e1rKeyTyped(evt);
            }
        });
        esfera1.add(txt_e1r, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 20));

        jLabel3.setText("X");
        esfera1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 10, -1));

        jLabel4.setText("Y");
        esfera1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 10, -1));

        txt_e1y.setText("0");
        txt_e1y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_e1yActionPerformed(evt);
            }
        });
        txt_e1y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e1yKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e1yKeyTyped(evt);
            }
        });
        esfera1.add(txt_e1y, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jLabel5.setText("Z");
        esfera1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 10, -1));

        txt_e1z.setText("-1");
        txt_e1z.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e1zKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e1zKeyTyped(evt);
            }
        });
        esfera1.add(txt_e1z, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 30, 20));

        jLabel6.setText("Material:");
        esfera1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txt_e1x.setText("0");
        txt_e1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_e1xActionPerformed(evt);
            }
        });
        txt_e1x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e1xKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e1xKeyTyped(evt);
            }
        });
        esfera1.add(txt_e1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 20));

        radioBar1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        radioBar1.setMaximum(10);
        radioBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radioBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        radioBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioBar1StateChanged(evt);
            }
        });
        esfera1.add(radioBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 110, -1));

        jLabel7.setText("Radio:");
        esfera1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Aire", "Tierra", "Fuego" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        esfera1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        e1activa.setText("Activar");
        e1activa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1activaActionPerformed(evt);
            }
        });
        esfera1.add(e1activa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        PanelEsferas.add(esfera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 100));

        esfera2.setBackground(new java.awt.Color(255, 255, 255));
        esfera2.setBorder(javax.swing.BorderFactory.createTitledBorder("Esfera 2"));
        esfera2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Posicion:");
        esfera2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txt_e2r.setText("0.5");
        txt_e2r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e2rKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e2rKeyTyped(evt);
            }
        });
        esfera2.add(txt_e2r, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 20));

        jLabel24.setText("X");
        esfera2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 10, -1));

        jLabel25.setText("Y");
        esfera2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 10, -1));

        txt_e2y.setText("0");
        txt_e2y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e2yKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e2yKeyTyped(evt);
            }
        });
        esfera2.add(txt_e2y, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jLabel26.setText("Z");
        esfera2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 10, -1));

        txt_e2z.setText("-1");
        txt_e2z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_e2zActionPerformed(evt);
            }
        });
        txt_e2z.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e2zKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e2zKeyTyped(evt);
            }
        });
        esfera2.add(txt_e2z, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 30, 20));

        jLabel27.setText("Material:");
        esfera2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txt_e2x.setText("-1");
        txt_e2x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_e2xActionPerformed(evt);
            }
        });
        txt_e2x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e2xKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e2xKeyTyped(evt);
            }
        });
        esfera2.add(txt_e2x, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 20));

        radioBar2.setMaximum(10);
        radioBar2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioBar2StateChanged(evt);
            }
        });
        esfera2.add(radioBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 110, -1));

        jLabel28.setText("Radio:");
        esfera2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Aire", "Tierra", "Fuego" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        esfera2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        e2activa.setText("Activar");
        e2activa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2activaActionPerformed(evt);
            }
        });
        esfera2.add(e2activa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        PanelEsferas.add(esfera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 360, 100));

        esfera3.setBackground(new java.awt.Color(255, 255, 255));
        esfera3.setBorder(javax.swing.BorderFactory.createTitledBorder("Esfera 3"));
        esfera3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Posicion:");
        esfera3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txt_e3r.setText("0.5");
        txt_e3r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e3rKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e3rKeyTyped(evt);
            }
        });
        esfera3.add(txt_e3r, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 20));

        jLabel9.setText("X");
        esfera3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 10, -1));

        jLabel10.setText("Y");
        esfera3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 10, -1));

        txt_e3y.setText("0");
        txt_e3y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e3yKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e3yKeyTyped(evt);
            }
        });
        esfera3.add(txt_e3y, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jLabel11.setText("Z");
        esfera3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 10, -1));

        txt_e3z.setText("-1");
        txt_e3z.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e3zKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e3zKeyTyped(evt);
            }
        });
        esfera3.add(txt_e3z, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 30, 20));

        jLabel12.setText("Material:");
        esfera3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txt_e3x.setText("1");
        txt_e3x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_e3xKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_e3xKeyTyped(evt);
            }
        });
        esfera3.add(txt_e3x, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 30, 20));

        radioBar3.setMaximum(10);
        radioBar3.setPaintLabels(true);
        radioBar3.setToolTipText("");
        radioBar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radioBar3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioBar3StateChanged(evt);
            }
        });
        esfera3.add(radioBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 110, -1));

        jLabel13.setText("Radio:");
        esfera3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Aire", "Tierra", "Fuego" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        esfera3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        e3activa.setText("Activar");
        e3activa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3activaActionPerformed(evt);
            }
        });
        esfera3.add(e3activa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        PanelEsferas.add(esfera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 360, 100));

        base.setText("Base");
        base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseActionPerformed(evt);
            }
        });
        PanelEsferas.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        Principal.add(PanelEsferas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 450, 360));

        PanelCamara.setBackground(new java.awt.Color(246, 255, 255));
        PanelCamara.setBorder(javax.swing.BorderFactory.createTitledBorder("Camara"));
        PanelCamara.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Posicion de la camara:");
        PanelCamara.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_Cz1.setText("1");
        txt_Cz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cz1ActionPerformed(evt);
            }
        });
        txt_Cz1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Cz1KeyTyped(evt);
            }
        });
        PanelCamara.add(txt_Cz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 30, 20));

        jLabel16.setText("Z");
        PanelCamara.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 10, -1));

        txt_Cy1.setText("2");
        txt_Cy1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Cy1KeyTyped(evt);
            }
        });
        PanelCamara.add(txt_Cy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 30, 20));

        jLabel15.setText("Y");
        PanelCamara.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 10, -1));

        jLabel14.setText("X");
        PanelCamara.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 10, -1));

        txt_Cx1.setText("-2");
        txt_Cx1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Cx1KeyTyped(evt);
            }
        });
        PanelCamara.add(txt_Cx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 30, 20));

        jLabel17.setText("Rotacion de la camara:");
        PanelCamara.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_Rx.setText("0");
        txt_Rx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RxKeyTyped(evt);
            }
        });
        PanelCamara.add(txt_Rx, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 30, 20));

        jLabel18.setText("X");
        PanelCamara.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 10, -1));

        jLabel19.setText("Y");
        PanelCamara.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 10, -1));

        txt_Ry.setText("0");
        txt_Ry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RyKeyTyped(evt);
            }
        });
        PanelCamara.add(txt_Ry, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 30, 20));

        jLabel20.setText("Z");
        PanelCamara.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 10, -1));

        txt_Rz.setText("-1");
        txt_Rz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RzActionPerformed(evt);
            }
        });
        txt_Rz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RzKeyTyped(evt);
            }
        });
        PanelCamara.add(txt_Rz, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 30, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PanelCamara.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 10, 140));

        jLabel21.setText("FOV");
        PanelCamara.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel22.setText("Vertical:");
        PanelCamara.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        Vertical.setText("20");
        Vertical.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VerticalKeyTyped(evt);
            }
        });
        PanelCamara.add(Vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 40, -1));

        Principal.add(PanelCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 460, 190));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Principal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        jLayeredPane1.add(Principal);
        Principal.setBounds(0, 0, 1150, 690);
        Principal.getAccessibleContext().setAccessibleName("Principal");

        jMenu1.setText("Principal");

        jMenuItem1.setText("Nuevo Renderizado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar Renderizado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuracion");
        jMenu2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jMenu2ComponentMoved(evt);
            }
        });

        jMenuItem3.setText("Configuracion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setLabel("Materiales");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setLabel("Materiales");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_imagenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lb_imagenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_imagenAncestorAdded

    private void jMenu2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenu2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ComponentMoved

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void e1activaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1activaActionPerformed
 imagen();
    }//GEN-LAST:event_e1activaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        imagen();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioBar1StateChanged
        txt_e1r.setText(Integer.toString(radioBar1.getValue()));
        
    }//GEN-LAST:event_radioBar1StateChanged

    private void radioBar2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioBar2StateChanged
        txt_e2r.setText(Integer.toString(radioBar2.getValue()));
       
    }//GEN-LAST:event_radioBar2StateChanged

    private void radioBar3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioBar3StateChanged
        txt_e3r.setText(Integer.toString(radioBar3.getValue()));
       
    }//GEN-LAST:event_radioBar3StateChanged

    private void txt_e1rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1rKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e1rKeyTyped

    private void txt_e1xKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1xKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e1xKeyTyped

    private void txt_e1yKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1yKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e1yKeyTyped

    private void txt_e1zKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1zKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e1zKeyTyped

    private void txt_e2xKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2xKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e2xKeyTyped

    private void txt_e2yKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2yKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e2yKeyTyped

    private void txt_e2zKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2zKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e2zKeyTyped

    private void txt_e2rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2rKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e2rKeyTyped

    private void txt_e3xKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3xKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e3xKeyTyped

    private void txt_e3yKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3yKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e3yKeyTyped

    private void txt_e3zKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3zKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
    }//GEN-LAST:event_txt_e3zKeyTyped

    private void txt_e3rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3rKeyTyped
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();      
    }//GEN-LAST:event_txt_e3rKeyTyped

    private void txt_Cx1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Cx1KeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
    }//GEN-LAST:event_txt_Cx1KeyTyped

    private void txt_Cy1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Cy1KeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
    }//GEN-LAST:event_txt_Cy1KeyTyped

    private void txt_Cz1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Cz1KeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();
    }//GEN-LAST:event_txt_Cz1KeyTyped

    private void txt_RxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RxKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46) || (key == 45);
        if(!numero)evt.consume();    }//GEN-LAST:event_txt_RxKeyTyped

    private void txt_RyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RyKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46)|| (key == 45);
        if(!numero)evt.consume();    }//GEN-LAST:event_txt_RyKeyTyped

    private void txt_RzKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RzKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46)|| (key == 45);
        if(!numero)evt.consume();    }//GEN-LAST:event_txt_RzKeyTyped

    private void VerticalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VerticalKeyTyped
        int key = evt.getKeyChar();
        boolean numero = (key >= 48 && key <=57)|| (key == 46)|| (key == 45);
        if(!numero)evt.consume();    }//GEN-LAST:event_VerticalKeyTyped

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO
        renderer.materiales();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        renderer.configuracion();
        //this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
//            archivo=seleccionar.getSelectedFile();
//            
//                String respuesta = Guardar();
//                if (respuesta!=null) {
//                    JOptionPane.showMessageDialog(null, respuesta);
//                }else{
//                    JOptionPane.showMessageDialog(null, "Archivo no guardado");
//                }
//            
//        }

JOptionPane.showMessageDialog(null, "Error 404, funcionalidad en construcion");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txt_e1rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_e1rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_e1rActionPerformed

    private void txt_e1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_e1xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_e1xActionPerformed

    private void txt_e1yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_e1yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_e1yActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO
        System.out.println("[TODO]: No ha sido implementado todavía");
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void txt_e2xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_e2xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_e2xActionPerformed

    private void txt_e2zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_e2zActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_e2zActionPerformed

    private void txt_Cz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cz1ActionPerformed

    private void txt_RzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RzActionPerformed

    private void txt_e3rKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3rKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e3rKeyPressed

    private void txt_e3xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3xKeyPressed
     if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e3xKeyPressed

    private void txt_e3yKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3yKeyPressed
       if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e3yKeyPressed

    private void txt_e3zKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e3zKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e3zKeyPressed

    private void txt_e2rKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2rKeyPressed
       if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e2rKeyPressed

    private void txt_e2xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2xKeyPressed
       if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e2xKeyPressed

    private void txt_e2yKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2yKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e2yKeyPressed

    private void txt_e2zKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e2zKeyPressed
       if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e2zKeyPressed

    private void txt_e1rKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1rKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e1rKeyPressed

    private void txt_e1xKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1xKeyPressed
       if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e1xKeyPressed

    private void txt_e1yKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1yKeyPressed
        if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e1yKeyPressed

    private void txt_e1zKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_e1zKeyPressed
       if (evt.getExtendedKeyCode()==VK_ENTER) imagen();  
    }//GEN-LAST:event_txt_e1zKeyPressed

    private void e2activaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2activaActionPerformed
     imagen();        // TODO add your handling code here:
    }//GEN-LAST:event_e2activaActionPerformed

    private void e3activaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3activaActionPerformed
     imagen();        // TODO add your handling code here:
    }//GEN-LAST:event_e3activaActionPerformed

    private void baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseActionPerformed
        imagen();
    }//GEN-LAST:event_baseActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RayTracerUI ui2 = new RayTracerUI(renderer);
        
        ui2.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RayTracerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RayTracerUI(renderer).setVisible(true);
            }
        });
        
        
        
    }
private void imagen(){
    if (this.scene == null) {
        
        this.scene = Scene.getSampleScene(config);
        renderBuffer = renderer.render(this.scene);
        this.lb_imagen.setIcon(new ImageIcon(renderBuffer));
    }else {
        
        if(e1activa.isSelected()){
            v1x = Double.parseDouble(txt_e1x.getText());
            v1y = Double.parseDouble(txt_e1y.getText());
            v1z = Double.parseDouble(txt_e1z.getText());
            v1r = Double.parseDouble(txt_e1r.getText());
            
        }else{
            v1x =0;
            v1y =0;
            v1z =0;
            v1r =0;
        }
        if(e2activa.isSelected()){
            v2x = Double.parseDouble(txt_e2x.getText());
            v2y = Double.parseDouble(txt_e2y.getText());
            v2z = Double.parseDouble(txt_e2z.getText());
            v2r = Double.parseDouble(txt_e2r.getText());
            
        }else{
            v2x =0;
            v2y =0;
            v2z =0;
            v2r =0;
        }
        if(e3activa.isSelected()){
            v3x = Double.parseDouble(txt_e3x.getText());
            v3y = Double.parseDouble(txt_e3y.getText());
            v3z = Double.parseDouble(txt_e3z.getText());
            v3r = Double.parseDouble(txt_e3r.getText());
            
        }else{
            v3x =0;
            v3y =0;
            v3z =0;
            v3r =0;
        }
        
            Cx=Double.parseDouble(txt_Cx1.getText());
            Cy=Double.parseDouble(txt_Cy1.getText());
            Cz=Double.parseDouble(txt_Cz1.getText());
            Rx=Double.parseDouble(txt_Rx.getText());
            Ry=Double.parseDouble(txt_Ry.getText());
            Rz=Double.parseDouble(txt_Rz.getText());
            if(base.isSelected()){
                siono = true;
            }else{
                siono=false;
            }
            config = new Config(Integer.parseInt(Configuracion.Ancho.getText()), Double.parseDouble(Configuracion.aspecto.getText()), Integer.parseInt(Configuracion.pixel.getText()), 20);
            this.scene = Scene.getUpdateScene(siono, config, v1x, v1y, v1z, v1r, v2x, v2y, v2z, v2r, v3x, v3y, v3z, v3r,  Cx, Cy, Cz, Rx, Ry, Rz);
            renderBuffer = renderer.render(this.scene);
            this.lb_imagen.setIcon(new ImageIcon(renderBuffer));
            
      
    }
}

private BufferedImage renderBuffer;
private double v1r,  v2r,  v3r, v1x,  v1y,  v1z,  v2x,  v2y,  v2z, v3x, v3y, v3z,Cx,Cy,Cz,Rx,Ry,Rz;
private final Renderer renderer;
private Scene scene;
private boolean siono;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCamara;
    private javax.swing.JPanel PanelEsferas;
    private javax.swing.JPanel Principal;
    private javax.swing.JTextField Vertical;
    private javax.swing.JCheckBox base;
    private javax.swing.JCheckBox e1activa;
    private javax.swing.JCheckBox e2activa;
    private javax.swing.JCheckBox e3activa;
    private javax.swing.JPanel esfera1;
    private javax.swing.JPanel esfera2;
    private javax.swing.JPanel esfera3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_imagen;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JSlider radioBar1;
    private javax.swing.JSlider radioBar2;
    private javax.swing.JSlider radioBar3;
    private javax.swing.JTextField txt_Cx1;
    private javax.swing.JTextField txt_Cy1;
    private javax.swing.JTextField txt_Cz1;
    private javax.swing.JTextField txt_Rx;
    private javax.swing.JTextField txt_Ry;
    private javax.swing.JTextField txt_Rz;
    private javax.swing.JTextField txt_e1r;
    private javax.swing.JTextField txt_e1x;
    private javax.swing.JTextField txt_e1y;
    private javax.swing.JTextField txt_e1z;
    private javax.swing.JTextField txt_e2r;
    private javax.swing.JTextField txt_e2x;
    private javax.swing.JTextField txt_e2y;
    private javax.swing.JTextField txt_e2z;
    private javax.swing.JTextField txt_e3r;
    private javax.swing.JTextField txt_e3x;
    private javax.swing.JTextField txt_e3y;
    private javax.swing.JTextField txt_e3z;
    // End of variables declaration//GEN-END:variables
}
